name: UpdatePriceDB
on:
  workflow_dispatch:
  schedule:
    - cron:  '00 14 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: update pricedb
        shell: pwsh
        run: |
            ./update-pricedb.ps1
      - uses: stefanzweifel/git-auto-commit-action@v4
