name: UpdatePriceDB
on:
  workflow_dispatch:
  schedule:
    - cron:  '30 16 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: tgju daily update
        shell: pwsh
        run: |
            ./src/tgju/update-daily.ps1

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_author: Author <actions@github.com>
